
/**************************************************************
 *	
 *	GameSong, 8 bit, 11025Hz,
 *	1 channel, 436032 bytes/channel
 *	Total Size: 1 * 436032 + 4 (header) = 436076 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Bang/Desktop/M22/GameSong.wav
 *	Time-stamp: Tue Nov 28 19:46:04 2017
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 436032

extern const unsigned char GameSong[436032];

#endif /* __GAMESONGH__ */
