
/**************************************************************
 *	
 *	HitSound, 8 bit, 11025Hz,
 *	1 channel, 8749 bytes/channel
 *	Total Size: 1 * 8749 + 4 (header) = 8793 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Bang/Desktop/M22/HitSound.wav
 *	Time-stamp: Tue Nov 28 19:45:53 2017
 *	
 **************************************************************/

#ifndef __HITSOUNDH__
#define __HITSOUNDH__

#define HITSOUNDFREQ 11025
#define HITSOUNDLEN 8749

extern const unsigned char HitSound[8749];

#endif /* __HITSOUNDH__ */
