
/**************************************************************
 *	
 *	TitleSong, 8 bit, 11025Hz,
 *	1 channel, 507456 bytes/channel
 *	Total Size: 1 * 507456 + 4 (header) = 507500 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Bang/Desktop/M22/TitleSong.wav
 *	Time-stamp: Tue Nov 28 19:45:37 2017
 *	
 **************************************************************/

#ifndef __TITLESONGH__
#define __TITLESONGH__

#define TITLESONGFREQ 11025
#define TITLESONGLEN 507456

extern const unsigned char TitleSong[507456];

#endif /* __TITLESONGH__ */
